# Site settings
title: Better Arguruments
tagline:
email: hi@betterarguruments.com
description: > # this means to ignore newlines until "baseurl:"
  Better Arguruments is an open source, mobile first, transparent collaboration
  that aims to build lightweight, fast and aesthetic apps to enhance everyday
  life in areas you don't expect.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://betterarguruments.github.io" # the base hostname & protocol for your site
twitter_username: BtrArguruments
github_username:  BetterArguruments

# Build settings
markdown: kramdown

projects:
  - title: 'NofApp'
    url: /nofapp/
  - title: 'NofApp Web'
    url: http://nofapp.com
    global: true
